targetNamespace: ''
parameters: {}
packages:
  - name: src
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: main
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
